development: &development
  adapter:   mysql2
  encoding:  utf8
  reconnect: false
  pool:      5
  database: curate_development
  host:     localhost
  timeout: 5000

development_remote_purl_database:
  <<: *development

test: &test
  <<: *development
  database: curate_test

test_remote_purl_database:
  <<: *test

ci: &ci
  <<: *test

ci_remote_purl_database:
  <<: *ci